# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.9
clone:
  depth: full

pipelines:
  branches:
    master:
      - step:
          caches:
            - maven
          script: # Modify the commands below to build your repository.
          - git submodule update --init --recursive
          - mvn -b clean install # -B batch mode makes Maven less verbose
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
        - git submodule update --init --recursive
        - mvn -b clean install # -B batch mode makes Maven less verbose
